### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by masterchop** [mikeferguson/ar_kinect#5]
I am working with Unity3d and i want to use my kinect for AR, i dont seem to understand this project, we need to compile it and they add the output somewhere else? could you please provide instalation isntructions Windows or Linux :)

**Comment by mikeferguson** [comment]
@masterchop -- this is a ROS package, which means you need to be using the Robot Operating System (ROS) (http://www.ros.org) and then this package is easy to install. ROS only really works on Linux.

**Comment by masterchop** [comment]
I guess my implementation plans for unity are all death. Thank you for your reply
